#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width          2
bspc config window_gap            12

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config focused_border_color  "#A6E3A1"
bspc config normal_border_color   "#1E1E2E"

bspc config external_rules_command "/home/$USER/.config/bspwm/external_rules"

picom &
lxpolkit &
dunst &
feh --bg-fill "/home/$USER/Pictures/background.png"

$HOME/.config/polybar/launch.sh &
